import Link from "next/link";
import { ArrowRight, BadgeCheck, Building2, GraduationCap, Mic2, Presentation, Users } from "lucide-react";

export default function AudiencePathways() {
  return <section className="bg-white px-5 py-16 sm:px-8 sm:py-20 lg:px-12"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-sm font-extrabold uppercase tracking-[.2em] text-[#00A866]">Choose your path</p><h2 className="mt-4 text-3xl font-extrabold text-[#062B5C] sm:text-5xl">One goal: confident communication. Two focused journeys.</h2></div><div className="mt-10 grid gap-6 lg:grid-cols-2">
    <article className="rounded-[2rem] bg-[#E9FFF5] p-7 sm:p-10"><GraduationCap size={36} className="text-[#008A55]"/><p className="mt-6 text-sm font-extrabold uppercase tracking-wider text-[#008A55]">7-week individual programme</p><h3 className="mt-3 text-3xl font-extrabold text-[#062B5C]">Build the confidence to be heard.</h3><div className="mt-6 grid gap-3 sm:grid-cols-2">{[[Mic2,"Real-time speaking"],[Presentation,"Presentations and GDs"],[BadgeCheck,"Interview readiness"],[Users,"Workplace conversations"]].map(([Icon,text])=>{const I=Icon as typeof Mic2;return <p key={text as string} className="flex items-center gap-2 font-semibold text-slate-700"><I size={19} className="text-[#00A866]"/>{text as string}</p>})}</div><Link href="/#learning-journey" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-[#00D97E] px-5 py-3 font-extrabold text-[#062B5C]">Explore the 7-week journey <ArrowRight size={18}/></Link></article>
    <article className="rounded-[2rem] bg-[#062B5C] p-7 text-white sm:p-10"><Building2 size={36} className="text-[#00D97E]"/><p className="mt-6 text-sm font-extrabold uppercase tracking-wider text-[#00D97E]">15-day campus bootcamp</p><h3 className="mt-3 text-3xl font-extrabold">Turn communication practice into placement readiness.</h3><div className="mt-6 grid gap-3 sm:grid-cols-2">{["Daily speaking practice","Presentations and GDs","Interview simulations","Pre/post cohort insight"].map(text=><p key={text} className="flex items-center gap-2 font-semibold text-blue-100"><BadgeCheck size={19} className="text-[#00D97E]"/>{text}</p>)}</div><Link href="/institutions#bootcamp" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 font-extrabold text-[#062B5C]">View the 15-day plan <ArrowRight size={18}/></Link></article>
  </div></div></section>;
}
