import Link from "next/link";
import { ArrowRight, BriefcaseBusiness, MessageSquareText, Mic2, Presentation, Sparkles, Users } from "lucide-react";

const moments = [
  { Icon: Mic2, title: "Speak without freezing", text: "Start, structure and complete an answer without translating every line in your head." },
  { Icon: Users, title: "Contribute in group discussions", text: "Enter the conversation, build on ideas and disagree professionally." },
  { Icon: Presentation, title: "Present ideas with clarity", text: "Turn scattered thoughts into a confident opening, clear flow and memorable close." },
  { Icon: BriefcaseBusiness, title: "Handle interviews naturally", text: "Practise credible stories, follow-up questions and calm responses under pressure." },
  { Icon: MessageSquareText, title: "Communicate at work", text: "Ask questions, share updates, write professional messages and speak with colleagues." },
];

export default function PremiumSections() {
  return <>
    <section className="bg-[#062B5C] px-5 py-10 text-white sm:px-8 lg:px-12" aria-label="Unmute Pro highlights"><div className="mx-auto grid max-w-7xl gap-6 text-center sm:grid-cols-3"><div><p className="text-4xl font-extrabold text-[#00D97E]">15+</p><p className="mt-1 text-sm text-blue-100">Years of corporate experience</p></div><div><p className="text-4xl font-extrabold text-[#00D97E]">Live</p><p className="mt-1 text-sm text-blue-100">Speaking and feedback practice</p></div><div><p className="text-4xl font-extrabold text-[#00D97E]">Goal-led</p><p className="mt-1 text-sm text-blue-100">Campus, interview and career scenarios</p></div></div></section>
    <section id="why-us" className="scroll-mt-32 bg-[#F7FAFE] px-5 py-16 sm:px-8 sm:py-20 lg:px-12"><div className="mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-[.72fr_1.28fr]"><div><span className="inline-flex items-center gap-2 rounded-full bg-[#E4FFF2] px-4 py-2 text-sm font-extrabold text-[#007F4D]"><Sparkles size={16}/> Built for real moments</span><h2 className="mt-5 text-3xl font-extrabold text-[#062B5C] sm:text-5xl">Communication practice that moves beyond grammar.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Learners do not need another lecture. They need safe, repeated practice for the moments where confidence matters.</p><Link href="/assessment" className="mt-7 inline-flex items-center gap-2 font-extrabold text-[#008A55]">Find your starting point <ArrowRight size={18}/></Link></div><div className="grid gap-4 sm:grid-cols-2">{moments.map(({Icon,title,text},index)=><article key={title} className={`rounded-3xl p-6 ${index===4?"bg-[#062B5C] text-white sm:col-span-2":"border border-slate-200 bg-white"}`}><Icon size={28} className="text-[#00D97E]"/><h3 className="mt-4 text-xl font-extrabold">{title}</h3><p className={`mt-2 leading-7 ${index===4?"text-blue-100":"text-slate-600"}`}>{text}</p></article>)}</div></div></div></section>
    <section className="bg-white px-5 py-16 sm:px-8 sm:py-20 lg:px-12"><div className="mx-auto max-w-6xl"><div className="text-center"><p className="text-sm font-extrabold uppercase tracking-[.2em] text-[#00A866]">A practical learning loop</p><h2 className="mt-4 text-3xl font-extrabold text-[#062B5C] sm:text-5xl">Learn less. Practise more. Reflect fast.</h2></div><div className="relative mt-12 grid gap-5 md:grid-cols-4">{[["01","Diagnose","Identify confidence gaps and priority situations."],["02","Model","See a clear structure and hear an effective example."],["03","Practise","Respond in real time through guided scenarios."],["04","Improve","Use mentor feedback and repeat with greater clarity."]].map(([number,title,text])=><article key={number} className="relative rounded-3xl border border-slate-200 bg-[#F8FBFF] p-6"><span className="text-4xl font-black text-[#00D97E]">{number}</span><h3 className="mt-4 text-xl font-extrabold text-[#062B5C]">{title}</h3><p className="mt-2 leading-7 text-slate-600">{text}</p></article>)}</div></div></section>
    <section className="bg-[#00D97E] px-5 py-12 sm:px-8 lg:px-12"><div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-6 text-center lg:flex-row lg:text-left"><div><p className="text-sm font-extrabold uppercase tracking-wider text-[#064E3B]">Start with a useful result</p><h2 className="mt-2 text-3xl font-extrabold text-[#062B5C]">Discover your level and the next skill to practise.</h2></div><Link href="/assessment" className="inline-flex shrink-0 items-center gap-2 rounded-xl bg-[#062B5C] px-7 py-4 font-extrabold text-white">Take the free level check <ArrowRight size={19}/></Link></div></section>
  </>;
}

