import Link from "next/link";

export const metadata = { title: "Delete Your Account", description: "Request deletion of your Unmute Pro learner account and associated data." };

export default function AccountDeletionPage() {
  const subject=encodeURIComponent("Unmute Pro account deletion request");
  const body=encodeURIComponent("Hello Unmute Pro,\n\nPlease delete my learner account and associated personal data.\n\nAccount email:\nAccount name:\nMobile number (if provided):\n\nI understand you may contact me to verify this request.");
  return <main className="min-h-screen bg-[#F4F8FC] px-5 py-10 text-[#062B5C]"><article className="mx-auto max-w-3xl rounded-3xl bg-white p-7 shadow-sm sm:p-12"><Link href="/app" className="font-bold text-[#008A55]">← Back to learner app</Link><p className="mt-8 text-sm font-extrabold uppercase tracking-wider text-[#00A866]">Your data, your choice</p><h1 className="mt-2 text-4xl font-extrabold sm:text-5xl">Delete your Unmute Pro account</h1><p className="mt-5 leading-8 text-slate-600">You can request deletion of your learner account and associated personal data at any time.</p><ol className="mt-8 space-y-4"><li className="rounded-2xl bg-slate-50 p-5"><strong>1. Send the request</strong><p className="mt-2 text-slate-600">Use the button below from the email address connected to your learner account.</p></li><li className="rounded-2xl bg-slate-50 p-5"><strong>2. Verify ownership</strong><p className="mt-2 text-slate-600">We may contact you to verify the request and protect your account.</p></li><li className="rounded-2xl bg-slate-50 p-5"><strong>3. Deletion is completed</strong><p className="mt-2 text-slate-600">After verification, we aim to remove the account and associated learner profile, progress and enquiry data within 30 days, except information we must retain for security, legal or accounting obligations.</p></li></ol><a href={`mailto:unmuteproofficial@gmail.com?subject=${subject}&body=${body}`} className="mt-8 inline-flex rounded-xl bg-[#00D97E] px-6 py-4 font-extrabold">Email my deletion request</a><p className="mt-5 text-sm leading-6 text-slate-500">If you cannot access your account email, contact us at +91 93922 09162 and provide enough information for us to verify ownership.</p><p className="mt-7 border-t border-slate-100 pt-6 text-sm"><Link href="/privacy" className="font-bold text-[#008A55]">Read the Privacy Policy</Link></p></article></main>;
}
