import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BarChart3, BadgeCheck, BookOpenCheck, Building2, CalendarDays, CheckCircle2, Download, FileText, GraduationCap, Mic2, Presentation, Users } from "lucide-react";
import InstitutionEnquiry from "@/components/InstitutionEnquiry";

export const metadata: Metadata = { title: "15-Day College Communication & Placement Bootcamp", description: "A practical 15-day communication, interview and placement-readiness bootcamp for colleges and institutions." , alternates:{canonical:"/institutions"} };

const programmes = [
  { Icon: Mic2, title: "15-Day Campus Communication Bootcamp", format: "Flagship · 15 training days", text: "A complete cohort journey across speaking confidence, presentations, group discussions, interviews and workplace communication.", featured: true },
  { Icon: GraduationCap, title: "Placement Readiness Lab", format: "Focused module", text: "Self-introductions, interview stories, mock interviews, body language and recruiter conversations.", featured: false },
  { Icon: Users, title: "SpeakUp Campus Club", format: "Ongoing practice", text: "Peer speaking challenges, mentor sessions and a repeatable communication-practice culture.", featured: false },
  { Icon: Building2, title: "First Job Communication", format: "Career launch", text: "Meetings, email, status updates, feedback, workplace etiquette and confident collaboration.", featured: false },
];

const bootcampPhases = [
  { days: "Days 1–3", Icon: BarChart3, title: "Baseline & Confidence Reset", text: "Identify current communication gaps, confidence barriers and priority placement situations." },
  { days: "Days 4–6", Icon: Mic2, title: "Everyday Speaking & Fluency", text: "Build clear sentences, conversation flow, listening responses and confident peer interaction." },
  { days: "Days 7–9", Icon: Presentation, title: "Presentations & Group Discussions", text: "Structure ideas, speak to a group, participate in GDs and give clear supporting reasons." },
  { days: "Days 10–12", Icon: GraduationCap, title: "Interview Communication", text: "Practise self-introductions, achievement stories, common questions, body language and mock interviews." },
  { days: "Days 13–15", Icon: Building2, title: "Workplace Readiness & Capstone", text: "Handle meetings, updates and feedback, then complete a final simulation and progress review." },
];

export default function InstitutionsPage() {
  return <main id="home" className="bg-white text-[#062B5C]">
    <header className="sticky top-0 z-40 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-3 sm:px-8"><Link href="/" className="rounded-lg bg-white"><Image src="/images/logo.png" alt="Unmute Pro" width={135} height={52} className="h-auto w-[120px]" priority/></Link><nav className="hidden items-center gap-7 text-sm font-bold md:flex"><a href="#bootcamp">15-Day Bootcamp</a><a href="#outcomes">Outcomes</a><a href="#institutions">Request proposal</a></nav><a href="#institutions" className="rounded-xl bg-[#00D97E] px-4 py-3 text-sm font-extrabold">Get a campus proposal</a></div></header>
    <section className="relative overflow-hidden bg-[#062B5C] px-5 py-16 text-white sm:px-8 sm:py-20 lg:px-12"><div className="absolute -right-32 top-0 h-96 w-96 rounded-full bg-[#00D97E]/15 blur-3xl"/><div className="relative mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.08fr_.92fr]"><div><p className="text-sm font-extrabold uppercase tracking-[.2em] text-[#00D97E]">15-day communication & placement bootcamp</p><h1 className="mt-5 text-4xl font-extrabold leading-tight sm:text-6xl">Build graduates who can explain what they know—and why it matters.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-blue-100">Fifteen training days of active speaking, presentations, group discussions, interview simulations and first-job communication—designed around your placement calendar.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="#institutions" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#00D97E] px-6 py-4 font-extrabold text-[#062B5C]">Request a bootcamp proposal <ArrowRight size={19}/></a><a href="/unmute-pro-campus-communication.pdf" download className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/25 px-6 py-4 font-extrabold"><Download size={19}/> Download programme deck</a></div><div className="mt-8 grid gap-3 sm:grid-cols-3">{["15 training days","Flexible college timetable","Pre/post cohort insight"].map(item=><p key={item} className="flex items-center gap-2 text-sm font-semibold text-blue-100"><CheckCircle2 size={17} className="text-[#00D97E]"/>{item}</p>)}</div></div><div className="relative"><div className="overflow-hidden rounded-[2rem] border-8 border-white/10"><div className="relative aspect-[4/3]"><Image src="/images/manibabu.jpg" alt="Manibabu, communication mentor for institutional programmes" fill sizes="(max-width:1024px) 100vw, 45vw" className="object-cover"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#031A38] to-transparent p-7 pt-24"><p className="text-2xl font-extrabold">Mentor-led by Manibabu</p><p className="mt-1 text-[#00D97E]">15+ years of corporate experience</p></div></div></div></div></div></section>
    <section id="programmes" className="scroll-mt-24 bg-[#F6F9FD] px-5 py-16 sm:px-8 sm:py-20 lg:px-12"><div className="mx-auto max-w-7xl"><p className="text-sm font-extrabold uppercase tracking-[.2em] text-[#00A866]">Campus solutions</p><div className="mt-4 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><h2 className="max-w-3xl text-3xl font-extrabold sm:text-5xl">Start with the 15-day flagship—or choose a focused module.</h2><p className="max-w-md leading-7 text-slate-600">Delivery can be adapted to department, year, current level, class size and placement calendar.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2">{programmes.map(({Icon,title,format,text,featured})=><article key={title} className={`rounded-3xl p-7 sm:p-8 ${featured?"bg-[#062B5C] text-white shadow-xl":"border border-slate-200 bg-white"}`}><div className="flex items-start justify-between gap-4"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#00D97E] text-[#062B5C]"><Icon size={24}/></span><span className={`text-sm font-extrabold ${featured?"text-[#00D97E]":"text-[#008A55]"}`}>{format}</span></div><h3 className="mt-6 text-2xl font-extrabold">{title}</h3><p className={`mt-3 leading-7 ${featured?"text-blue-100":"text-slate-600"}`}>{text}</p>{featured&&<a href="#bootcamp" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[#00D97E] px-5 py-3 font-extrabold text-[#062B5C]">See all 15 days <ArrowRight size={18}/></a>}</article>)}</div></div></section>
    <section id="bootcamp" className="scroll-mt-24 bg-white px-5 py-16 sm:px-8 sm:py-20 lg:px-12">
      <div className="mx-auto max-w-7xl">
        <div className="mx-auto max-w-3xl text-center">
          <p className="text-sm font-extrabold uppercase tracking-[.2em] text-[#00A866]">The 15-day roadmap</p>
          <h2 className="mt-4 text-3xl font-extrabold sm:text-5xl">Five practical phases. One placement-ready transformation.</h2>
          <p className="mt-5 text-lg leading-8 text-slate-600">Each phase builds on the last, so students move from awareness to repeated practice and a final real-world performance.</p>
        </div>
        <div className="relative mt-12 grid gap-4 lg:grid-cols-5">
          <div className="absolute left-[10%] right-[10%] top-8 hidden h-0.5 bg-[#00D97E]/30 lg:block" />
          {bootcampPhases.map(({days,Icon,title,text},index)=><article key={days} className="relative rounded-3xl border border-slate-200 bg-[#F8FBFF] p-6 shadow-sm"><span className="grid h-16 w-16 place-items-center rounded-2xl bg-[#062B5C] text-[#00D97E] shadow-lg"><Icon size={27}/></span><p className="mt-5 text-xs font-extrabold uppercase tracking-wider text-[#00A866]">{days}</p><h3 className="mt-2 text-xl font-extrabold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p><span className="absolute right-5 top-5 text-4xl font-black text-[#00D97E]/30">{String(index+1).padStart(2,"0")}</span></article>)}
        </div>
        <div className="mt-8 grid gap-4 rounded-[2rem] bg-[#E9FFF5] p-6 sm:grid-cols-3 sm:p-8">{[[BarChart3,"Before","Baseline confidence and priority-skill snapshot"],[Mic2,"During","Daily participation and scenario-based speaking practice"],[FileText,"After","Final simulation, cohort insight and next-step recommendations"]].map(([Icon,stage,text])=>{const I=Icon as typeof BarChart3;return <div key={stage as string} className="flex items-start gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-white text-[#00A866]"><I size={22}/></span><div><p className="font-extrabold">{stage as string}</p><p className="mt-1 text-sm leading-6 text-slate-600">{text as string}</p></div></div>})}</div>
        <div className="mt-8 text-center"><a href="#institutions" className="inline-flex items-center gap-2 rounded-xl bg-[#00D97E] px-7 py-4 font-extrabold text-[#062B5C] shadow-lg transition hover:-translate-y-1">Request the 15-day bootcamp proposal <ArrowRight size={18}/></a></div>
      </div>
    </section>
    <section id="outcomes" className="scroll-mt-24 px-5 py-16 sm:px-8 sm:py-20 lg:px-12"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-extrabold uppercase tracking-[.2em] text-[#00A866]">Designed for accountability</p><h2 className="mt-4 text-3xl font-extrabold sm:text-5xl">A programme your placement team can see and use.</h2><p className="mt-5 text-lg leading-8 text-slate-600">The training plan can include baseline checks, participation visibility and a final cohort insight—not just session delivery.</p></div><div className="grid gap-4 sm:grid-cols-2">{[[BarChart3,"Pre/post snapshot","A clear view of starting confidence and priority skills."],[BookOpenCheck,"Scenario practice","Interviews, presentations, GDs and workplace conversations."],[FileText,"Cohort insight","A concise summary of engagement, common gaps and next steps."],[BadgeCheck,"Completion recognition","Certificates and learner-level completion visibility where agreed."]].map(([Icon,title,text])=>{const I=Icon as typeof BarChart3;return <article key={title as string} className="rounded-3xl bg-[#F6F9FD] p-6"><I size={27} className="text-[#00A866]"/><h3 className="mt-4 text-xl font-extrabold">{title as string}</h3><p className="mt-2 leading-7 text-slate-600">{text as string}</p></article>})}</div></div></section>
    <section className="bg-[#E9FFF5] px-5 py-16 sm:px-8 sm:py-20 lg:px-12"><div className="mx-auto max-w-6xl"><div className="text-center"><p className="text-sm font-extrabold uppercase tracking-[.2em] text-[#008A55]">Simple implementation</p><h2 className="mt-4 text-3xl font-extrabold sm:text-5xl">From campus need to confident practice.</h2></div><div className="mt-12 grid gap-6 md:grid-cols-4">{[[CalendarDays,"01","Discover","Clarify learner profile, placement calendar and priority outcomes."],[Presentation,"02","Design","Choose format, scenarios, schedule and reporting approach."],[Users,"03","Deliver","Run practical mentor-led sessions with active learner participation."],[FileText,"04","Review","Share completion visibility, cohort insight and next-step guidance."]].map(([Icon,num,title,text])=>{const I=Icon as typeof CalendarDays;return <article key={num as string}><I size={26} className="text-[#00A866]"/><p className="mt-5 text-4xl font-black text-[#00D97E]">{num as string}</p><h3 className="mt-2 text-xl font-extrabold">{title as string}</h3><p className="mt-2 leading-7 text-slate-600">{text as string}</p></article>})}</div></div></section>
    <InstitutionEnquiry/>
    <footer className="bg-[#031A38] px-5 py-10 text-white sm:px-8"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-5 text-center sm:flex-row sm:text-left"><div><Image src="/images/logo.png" alt="Unmute Pro" width={125} height={48} className="rounded-lg bg-white p-2"/><p className="mt-3 text-sm text-blue-100">Communication confidence for campus and career.</p></div><div className="text-sm text-blue-100"><p>unmuteproofficial@gmail.com · +91 93922 09162</p><p className="mt-2"><Link href="/privacy">Privacy Policy</Link> · <Link href="/account-deletion">Account deletion</Link></p></div></div></footer>
  </main>;
}
