import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BarChart3, BadgeCheck, BookOpenCheck, Building2, CalendarDays, CheckCircle2, Download, FileText, GraduationCap, Mic2, Presentation, Users } from "lucide-react";
import InstitutionEnquiry from "@/components/InstitutionEnquiry";

export const metadata: Metadata = { title: "College Communication & Placement Training", description: "Communication, interview and placement-readiness workshops and cohort programmes for colleges and institutions." , alternates:{canonical:"/institutions"} };

const programmes = [
  { Icon: Mic2, title: "Campus Communication Bootcamp", format: "4 or 8 weeks", text: "Speaking confidence, presentation structure, group discussions and professional expression." },
  { Icon: GraduationCap, title: "Placement Readiness Lab", format: "Cohort programme", text: "Self-introductions, interview stories, mock interviews, body language and recruiter conversations." },
  { Icon: Users, title: "SpeakUp Campus Club", format: "Ongoing practice", text: "Peer speaking challenges, mentor sessions and a repeatable communication-practice culture." },
  { Icon: Building2, title: "First Job Communication", format: "Career launch", text: "Meetings, email, status updates, feedback, workplace etiquette and confident collaboration." },
];

export default function InstitutionsPage() {
  return <main id="home" className="bg-white text-[#062B5C]">
    <header className="sticky top-0 z-40 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-3 sm:px-8"><Link href="/" className="rounded-lg bg-white"><Image src="/images/logo.png" alt="Unmute Pro" width={135} height={52} className="h-auto w-[120px]" priority/></Link><nav className="hidden items-center gap-7 text-sm font-bold md:flex"><a href="#programmes">Programmes</a><a href="#outcomes">Outcomes</a><a href="#institutions">Request presentation</a></nav><a href="#institutions" className="rounded-xl bg-[#00D97E] px-4 py-3 text-sm font-extrabold">Get a campus proposal</a></div></header>
    <section className="relative overflow-hidden bg-[#062B5C] px-5 py-16 text-white sm:px-8 sm:py-20 lg:px-12"><div className="absolute -right-32 top-0 h-96 w-96 rounded-full bg-[#00D97E]/15 blur-3xl"/><div className="relative mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.08fr_.92fr]"><div><p className="text-sm font-extrabold uppercase tracking-[.2em] text-[#00D97E]">For colleges, universities and placement teams</p><h1 className="mt-5 text-4xl font-extrabold leading-tight sm:text-6xl">Build graduates who can explain what they know—and why it matters.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-blue-100">Unmute Pro turns communication into repeatable practice for interviews, presentations, group discussions and the first months at work.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="#institutions" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#00D97E] px-6 py-4 font-extrabold text-[#062B5C]">Request a campus presentation <ArrowRight size={19}/></a><a href="/unmute-pro-campus-communication.pdf" download className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/25 px-6 py-4 font-extrabold"><Download size={19}/> Download programme deck</a></div><div className="mt-8 grid gap-3 sm:grid-cols-3">{["On-campus or online","One-day to eight-week formats","Placement-focused practice"].map(item=><p key={item} className="flex items-center gap-2 text-sm font-semibold text-blue-100"><CheckCircle2 size={17} className="text-[#00D97E]"/>{item}</p>)}</div></div><div className="relative"><div className="overflow-hidden rounded-[2rem] border-8 border-white/10"><div className="relative aspect-[4/3]"><Image src="/images/manibabu.jpg" alt="Manibabu, communication mentor for institutional programmes" fill sizes="(max-width:1024px) 100vw, 45vw" className="object-cover"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#031A38] to-transparent p-7 pt-24"><p className="text-2xl font-extrabold">Mentor-led by Manibabu</p><p className="mt-1 text-[#00D97E]">15+ years of corporate experience</p></div></div></div></div></div></section>
    <section id="programmes" className="scroll-mt-24 bg-[#F6F9FD] px-5 py-16 sm:px-8 sm:py-20 lg:px-12"><div className="mx-auto max-w-7xl"><p className="text-sm font-extrabold uppercase tracking-[.2em] text-[#00A866]">Campus solutions</p><div className="mt-4 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><h2 className="max-w-3xl text-3xl font-extrabold sm:text-5xl">Choose a focused workshop or build a complete cohort journey.</h2><p className="max-w-md leading-7 text-slate-600">Every format can be adapted to department, year, current level and placement calendar.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2">{programmes.map(({Icon,title,format,text},index)=><article key={title} className={`rounded-3xl p-7 sm:p-8 ${index===1?"bg-[#062B5C] text-white":"border border-slate-200 bg-white"}`}><div className="flex items-start justify-between gap-4"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#00D97E] text-[#062B5C]"><Icon size={24}/></span><span className={`text-sm font-extrabold ${index===1?"text-[#00D97E]":"text-[#008A55]"}`}>{format}</span></div><h3 className="mt-6 text-2xl font-extrabold">{title}</h3><p className={`mt-3 leading-7 ${index===1?"text-blue-100":"text-slate-600"}`}>{text}</p></article>)}</div></div></section>
    <section id="outcomes" className="scroll-mt-24 px-5 py-16 sm:px-8 sm:py-20 lg:px-12"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-extrabold uppercase tracking-[.2em] text-[#00A866]">Designed for accountability</p><h2 className="mt-4 text-3xl font-extrabold sm:text-5xl">A programme your placement team can see and use.</h2><p className="mt-5 text-lg leading-8 text-slate-600">The training plan can include baseline checks, participation visibility and a final cohort insight—not just session delivery.</p></div><div className="grid gap-4 sm:grid-cols-2">{[[BarChart3,"Pre/post snapshot","A clear view of starting confidence and priority skills."],[BookOpenCheck,"Scenario practice","Interviews, presentations, GDs and workplace conversations."],[FileText,"Cohort insight","A concise summary of engagement, common gaps and next steps."],[BadgeCheck,"Completion recognition","Certificates and learner-level completion visibility where agreed."]].map(([Icon,title,text])=>{const I=Icon as typeof BarChart3;return <article key={title as string} className="rounded-3xl bg-[#F6F9FD] p-6"><I size={27} className="text-[#00A866]"/><h3 className="mt-4 text-xl font-extrabold">{title as string}</h3><p className="mt-2 leading-7 text-slate-600">{text as string}</p></article>})}</div></div></section>
    <section className="bg-[#E9FFF5] px-5 py-16 sm:px-8 sm:py-20 lg:px-12"><div className="mx-auto max-w-6xl"><div className="text-center"><p className="text-sm font-extrabold uppercase tracking-[.2em] text-[#008A55]">Simple implementation</p><h2 className="mt-4 text-3xl font-extrabold sm:text-5xl">From campus need to confident practice.</h2></div><div className="mt-12 grid gap-6 md:grid-cols-4">{[[CalendarDays,"01","Discover","Clarify learner profile, placement calendar and priority outcomes."],[Presentation,"02","Design","Choose format, scenarios, schedule and reporting approach."],[Users,"03","Deliver","Run practical mentor-led sessions with active learner participation."],[FileText,"04","Review","Share completion visibility, cohort insight and next-step guidance."]].map(([Icon,num,title,text])=>{const I=Icon as typeof CalendarDays;return <article key={num as string}><I size={26} className="text-[#00A866]"/><p className="mt-5 text-4xl font-black text-[#00D97E]">{num as string}</p><h3 className="mt-2 text-xl font-extrabold">{title as string}</h3><p className="mt-2 leading-7 text-slate-600">{text as string}</p></article>})}</div></div></section>
    <InstitutionEnquiry/>
    <footer className="bg-[#031A38] px-5 py-10 text-white sm:px-8"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-5 text-center sm:flex-row sm:text-left"><div><Image src="/images/logo.png" alt="Unmute Pro" width={125} height={48} className="rounded-lg bg-white p-2"/><p className="mt-3 text-sm text-blue-100">Communication confidence for campus and career.</p></div><div className="text-sm text-blue-100"><p>unmuteproofficial@gmail.com · +91 93922 09162</p><p className="mt-2"><Link href="/privacy">Privacy Policy</Link> · <Link href="/account-deletion">Account deletion</Link></p></div></div></footer>
  </main>;
}

